name: senselet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  fcm_config: ^3.5.1
  graphql_flutter: ^5.1.2
  sizer: ^2.0.15
  firebase_analytics: ^10.1.6
  shared_preferences: ^2.0.20
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  shimmer: ^2.0.0
  country_picker: ^2.0.20
  pinput: ^2.2.31
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.0
  awesome_snackbar_content: ^0.1.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:

    - assets/images/doc.png
    - assets/images/p.png
    - assets/images/no.png
    - assets/images/pin.png
    - assets/images/me.png
    - assets/images/pharma.png
    - assets/images/logo.png
    - assets/images/logo_green.png
    - assets/images/sucess.png
    - assets/images/map.png
    - assets/images/drug.jpg
    - assets/lottie/

  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700


